# don't build tags, it's redundant
if: tag IS blank

git:
  depth: 3

language: node_js

node_js:
  - "12"
  - "10"
  - "8"

os:
  - linux

env:
  global:
    - NO_UPDATE_NOTIFIER=1
    - NODE_NO_WARNINGS=1

matrix:
  fast_finish: true
  # only run windows tests on latest node
  include:
    - os: windows
      node_js: "12"

cache: npm

before_install:
- |
  case "${TRAVIS_OS_NAME}" in
    "windows")
      # yarn isn't installed by default
      npm install --global yarn
    ;;
  esac

install: npm ci

before_script:
  - npm config set loglevel warn
  - git config --global user.email test@example.com
  - git config --global user.name "Tester McPerson"
  - yarn --version

script:
  - npm run ci
