# don't build tags, it's redundant
if: tag IS blank

git:
  depth: 3

language: node_js

node_js:
  - "12"
  - "10"
  - "8"

os:
  - linux

env:
  global:
    - NO_UPDATE_NOTIFIER=1
    - NODE_NO_WARNINGS=1
    - LERNA_CI_SCRIPT=ci

matrix:
  fast_finish: true
  # only run windows tests on latest node
  include:
    # run publish/version tests first (slower, higher priority)
    - os: windows
      node_js: "12"
      name: "Windows Tests (publish)"
      env:
        - LERNA_CI_SCRIPT="ci:windows"
        - LERNA_CI_TYPE="publish"

    # and then the rest of the tests (quicker, lower priority)
    - os: windows
      node_js: "12"
      name: "Windows Tests (non-publish)"
      env:
        - LERNA_CI_SCRIPT="ci:windows"
        - LERNA_CI_TYPE="non-publish"

cache: npm

before_install:
  - |
    case "${TRAVIS_OS_NAME}" in
      "windows")
        # yarn isn't installed by default
        npm install --global yarn
        # make git subcommands work again
        export PATH="/c/Program Files/Git/mingw64/bin:/c/Program Files/Git/mingw64/usr/bin:/c/Program Files/Git/mingw64/libexec/git-core:$PATH"
      ;;
    esac
  - npm install --global pnpm

install: pnpm recursive install

before_script:
  - npm config set loglevel warn
  - git config --global user.email test@example.com
  - git config --global user.name "Tester McPerson"
  - yarn --version

script:
  - pnpm run $LERNA_CI_SCRIPT
