# don't build tags, it's redundant
if: tag IS blank

git:
  depth: 3

language: node_js

node_js:
  - "10"
  - "8"

os:
  - linux
  - windows

env:
  global:
    - NO_UPDATE_NOTIFIER=1
    - NODE_NO_WARNINGS=1

matrix:
  fast_finish: true
  exclude:
    # only run windows CI on LTS (v10)
    - node_js: "8"
      os: windows

cache: npm

before_install:
  - if [[ "$(npm -v)" != "$(npm v npm dist-tags.latest)" ]]; then npm i -g npm@latest; fi
  # - set PATH=%APPDATA%\npm;"C:\Program Files\Git\mingw64\bin";%PATH%

install: npm ci

before_script:
  - npm config set loglevel warn
  - git config --global user.email test@example.com
  - git config --global user.name "Tester McPerson"
  - if [[ "$TRAVIS_OS_NAME" = "windows" ]]; then npm i -g yarn; fi

script:
  - npm run ci
