# don't build tags, it's redundant
skip_tags: true

shallow_clone: true

environment:
  NO_UPDATE_NOTIFIER: "1"
  NODE_NO_WARNINGS: "1"
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "8"
    - nodejs_version: "6"

matrix:
  fast_finish: true

cache:
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm config set loglevel warn
  - npm install --global npm@latest
  - set PATH=%APPDATA%\npm;"C:\Program Files\Git\mingw64\bin";%PATH%
  - npm ci

before_test:
  - git config --global user.email test@example.com
  - git config --global user.name "Tester McPerson"

test_script:
  - npm run ci

build: off
