# Test against this version of Node.js
environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "7"

init:
  - git config --global user.email test@example.com
  - git config --global user.name "Tester McPerson"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global npm@^3.0.0
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run ci

# Don't actually build.
build: off
