# path to a directory with all packages
storage: ../../../tmp/local-registry/storage

listen: localhost:4872

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    max_fails: 100
    maxage: 30m
    fail_timeout: 10m
    timeout: 600s
    cache: false

packages:
  "@lerna/*":
    access: $all
    publish: $all

  "**":
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

# log settings
logs:
  type: stdout
  format: pretty
  level: warn
